enquiry/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


from .views import send_enquiry

app_name = 'enquiry'

urlpatterns = [

    url(r'^$', send_enquiry, name='send'),
    url(r'^thanks/$', TemplateView.as_view(template_name="enquiry/thankyou.html"), name='thanks'),

]

users/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView

from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [

    url(r'^$', TemplateView.as_view(
        template_name='users/login_home.html'),
        name='users'),

    url(r'^login', auth_views.login, name='login'),

    url(r'^signup', views.SignUp.as_view(), name='signup'),

    # url(r'^login', views.LogIn.as_view(), name='login'),

]

website/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic.base import RedirectView

# Using the Django supplied auth views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from django.urls import path, include
from django.views.generic.base import TemplateView

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^cms/', include(wagtailadmin_urls)),

    url(r'^admin/', RedirectView.as_view(url="/cms/")),

    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url(r'^enquiry/', include('enquiry.urls'), name='enquiry'),

    path('users/', include('users.urls')),

    path('users/', include('django.contrib.auth.urls')),


    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),


    # Authentication

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enquiry/models.py
from django.db import models

# Create your models here.

enquiry/views.py
from django.shortcuts import redirect
from django.http import Http404
from django.urls import reverse_lazy

import sendgrid
from sendgrid.helpers.mail import *
from decouple import config


def send_enquiry(request):
    name = request.POST.get('enquiry_name', '')
    form_email = request.POST.get('enquiry_email', '')
    text = request.POST.get('enquiry_text', '')

    if form_email == '':
        raise Http404

# SendGrid API
    else:
        sg = sendgrid.SendGridAPIClient(apikey=config('SENDGRID_API_KEY'))
        from_email = Email(form_email)
        to_email = Email("filystyle@gmail.com")
        subject = "Enquiry from Drishti website"
        email_content = Content("text/plain", "Hello, " + name + " has an enquiry. \n" + text +
                                "\n My contact email is: " + str(from_email))

        new_mail = Mail(from_email, subject, to_email, email_content)
        response = sg.client.mail.send.post(request_body=new_mail.get())
        # print(response.status_code)
        # print(response.body)
        # print(response.headers)

        return redirect(reverse_lazy('enquiry:thanks'))

website/templates/partials/enquiry.html
{% load wagtailcore_tags %}

<section class="enquiry">

  <div class="enquiry__info">
    <h3>Want to ask a question?</h3>
  </div>

  <form class="enquiry__form" method="post" action="{% url 'enquiry:send' %}">
    {#      <form class="enquiry__form" method="post" action="">#}


    {% csrf_token %}

    <div class="form_input__row double">
      <div class="form_input">
        <label for="name">
          <input type="text" id="enquiry_name" name="enquiry_name" placeholder="Your name">
        </label>
      </div>

      <div class="form_input">
        <label for="email">
          <input type="email" id="enquiry_email" name="enquiry_email" placeholder="Your email">
        </label>
      </div>
    </div>

    <div class="form_input__row">
      <div class="form_input">
      <textarea name="enquiry_text" id="enquiry_text" cols="30" rows="10"
                placeholder="What's your question?"></textarea>
      </div>
    </div>

    <div class="form_input__row">
      <button class="button light" type="submit">submit</button>
    </div>
  </form>

</section>

website/templates/partials/footer.html
<div class="fix-bottom">

  {% include 'partials/enquiry.html' %}

  <footer class="footer" id="contact">

    <div class="lessons column">
      <h3>Latest Yoga Lessons</h3>

      {% for l in latest_lessons %}
        <a href="{{ l.url }}">{{ l }}</a>
      {% endfor %}
    </div>

    <div class="treatments column">
      <h3>Latest Health Treatments</h3>

      {% for t in latest_treatments %}
        <a href="{{ t.url }}">{{ t }}</a>
      {% endfor %}
    </div>

    <div class="contact column">
      <h3>Contact</h3>

      <p><a href="tel:07895995563">Tel: 07895 995563</a></p>

      <p><a href="mailto:anthearandell@hotmail.co.uk">Email: anthearandell@hotmail.co.uk</a></p>

      <p class="facebook"><a href="https://www.facebook.com/anthea.randell.3?ref=br_rs"><i
              class="fab fa-facebook-square"></i></a></p>

    </div>

  </footer>

</div>

website/templates/partials/google_map.html
<script async="false">

    window.initMap = function () {

        let myLatLng = {lat: {{ lat }}, lng: {{ lon }}};

        let myCenter = myLatLng;

        if (window.innerWidth > 500) {
          myCenter = {lat: {{ lat }}+0.001, lng: {{ lon }}-0.003 };
        }
        {#else let myCenter = myLatLng;#}

        let map = new google.maps.Map(document.getElementById('google-map'), {
            zoom: 14,
            center: myCenter,
            zoomControl: false,
            zoomControlOptions: {
                style: google.maps.ZoomControlStyle.SMALL
            },
            disableDoubleClickZoom: true,
            mapTypeControl: false,
            scaleControl: false,
            scrollwheel: true,
            panControl: true,
            streetViewControl: false,
            fullscreenControl: false,
            draggable: true,
            overviewMapControl: true,
            overviewMapControlOptions: {
                opened: false
            }
        });

        let marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            {#icon: '{{ STATIC_URL }}img/map-pin.png'#}
        });

        setTimeout(function() {

          console.log('Timeout?');

          google.maps.event.trigger(map, "resize");
          map.setCenter(myCenter);

        }, 2000);
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_4fXuQBbkudF5A0JgVfLv1cBwzxh57Hw&callback=initMap"></script>

website/templates/partials/menu.html
<nav class="menu">

  {% for p in pages %}
    <a href="{{ p.url }}">{{ p }}</a>
  {% endfor %}

  <a href="#contact">Contact</a>

</nav>